const REDUCER = "SIDEBAR_REDUCER_";
const SIDEBAR_REDUCER_ACTION_TYPE = {
    SET_ACTIVE : REDUCER + "SET_ACTIVE",
    ACCORDION_TOGGLE : REDUCER + "ACCORDION_TOGGLE"
}

export default SIDEBAR_REDUCER_ACTION_TYPE;
